import sdl2

keys = {
    sdl2.SDLK_a: "A",
    sdl2.SDLK_b: "B",
    sdl2.SDLK_c: "C",
    sdl2.SDLK_d: "D",
    sdl2.SDLK_e: "E",
    sdl2.SDLK_f: "F",
    sdl2.SDLK_g: "G",
    sdl2.SDLK_h: "H",
    sdl2.SDLK_i: "I",
    sdl2.SDLK_j: "J",
    sdl2.SDLK_k: "K",
    sdl2.SDLK_l: "L",
    sdl2.SDLK_m: "M",
    sdl2.SDLK_n: "N",
    sdl2.SDLK_o: "O",
    sdl2.SDLK_p: "P",
    sdl2.SDLK_q: "Q",
    sdl2.SDLK_r: "R",
    sdl2.SDLK_s: "S",
    sdl2.SDLK_t: "T",
    sdl2.SDLK_u: "U",
    sdl2.SDLK_v: "V",
    sdl2.SDLK_w: "W",
    sdl2.SDLK_x: "X",
    sdl2.SDLK_y: "Y",
    sdl2.SDLK_z: "Z"
}